### ISSUE TITLE
有UC答题的么

### ISSUE THREAD

**Issue by Yunnathai** [ZaneYork/hortor_qustion_bank#1]

**Comment by ZaneYork** [comment]
暂时没有的，最近没什么时间研究新的接口

**Comment by Yunnathai** [comment]
那这个头脑王者的题库 data.db 是最新爬的么~~

**Comment by ZaneYork** [comment]
初版是我自己抓的1W题，整合了外来的7k+题，最新的一版更新是我在天梯自动挂1天拿的，差不多600多题。目前还在继续挂机刷题，总新题数量大约在1k-2k。官方的题库逻辑分级了，天梯上的新题权重被拉高了，好友对战新题的权重极低

**Comment by Yunnathai** [comment]
好的。期待你的新题。其实UC的题库也蛮不错 可以试试

**Comment by Yunnathai** [comment]
兄弟 看了下最新的题库  为什么没有答案的其他选项呢 好像只有正确答案的选项  options字段

**Comment by ZaneYork** [comment]
一开始设计的没记录，现在要加也不太现实了。主要是如果是速查和记忆，显示全部选项意义不大，所以就没记录了。程序自动答的话，选项是直接在数据包里发过来的，直接索引一下就行了，也没必要

**Comment by Yunnathai** [comment]
能否出个 UC答题的抓包demo。 UC答题题库比较新，而且帮忙把所有选项都抓一下？~谢啦。

**Comment by ZaneYork** [comment]
看了下UC答题的数据包和源代码，数据包被加密处理了，源码是被混淆过的，破解需要时间

**Comment by Yunnathai** [comment]
好的 能帮我搞下吗。
